### ISSUE TITLE
css class names with periods don't work

### ISSUE THREAD

**Issue by tig** [ArthurHub/HTML-Renderer#168]
Consider

    <span class="token property">property</span>

This CSS should work, but doesn't:

``` css
     .token.property {
    	color: #c92c2c;
    }
```

But this does

``` css
     .property {
    	color: #c92c2c;
    }
```
