### ISSUE TITLE
CSS selector for wildcard classes does not work

### ISSUE THREAD

**Issue by tig** [ArthurHub/HTML-Renderer#169]
this is valid CSS
```css
code[class*="language-"],
pre[class*="language-"] {
	color: black;
}
```

Matches

```html
<code class="language-typescript">xyz</code>
````

HTML-Renderer ignores it.
